# Generated by Django 5.2.5 on 2025-08-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_assignment_student_assignment_submitted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Lecture", "Lecture"),
                            ("Lab", "Lab"),
                            ("Seminar", "Seminar"),
                            ("Tutorial", "Tutorial"),
                            ("Workshop", "Workshop"),
                        ],
                        default="Lecture",
                        max_length=20,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "time"],
                "unique_together": {("course", "day", "time")},
            },
        ),
    ]
