# Generated by Django 5.2.5 on 2025-08-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="emotion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                    ("surprised", "Surprised"),
                    ("neutral", "Neutral"),
                    ("fear", "Fear"),
                    ("disgust", "Disgust"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emotion",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "Normal"),
                    ("stressed", "Stressed"),
                    ("tired", "Tired"),
                    ("focused", "Focused"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
