# Generated by Django 5.2.5 on 2025-08-06 14:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emotion_emotion_alter_emotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.assignment_submission_file_path),
        ),
    ]
