# Generated by Django 5.2.5 on 2025-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_assignment_grade_remove_assignment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="detailed_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="improvement_suggestions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
